nmap <Space>v <Plug>(multiselect)
xmap <Space>v <Plug>(multiselect)
nmap <Space>V <Plug>(multiselect-uncheckall)
xmap <Space>V <Plug>(multiselect-uncheck)
nmap @/ <Plug>(multiselect-checksearched)
map [v <Plug>(multiselect-previous)
map ]v <Plug>(multiselect-next)
